# Simple pipeline to deploy static site to GitLab Pages
image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
